name: Keep Alive Ping

on:
  schedule:
    - cron: '*/5 * * * *'   # Запуск каждые 5 минут
  workflow_dispatch:        # Возможность ручного запуска

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping to backend
        run: curl -fsS --retry 3 https://ageinvest-backend.onrender.com || exit 1
